app:
  image:
    bucket: c:/tmp/pet_images

spring:
  liquibase:
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      client:
        registration:
          external:
            client-id: "my_client"
            client-secret: "dOrAUhZmOr66rHl7YQ5fJExAcqA03F8h"
            authorization-grant-type: client_credentials
        provider:
          external:
            token-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8484/auth}/realms/my_realm/protocol/openid-connect/token

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
